"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { slugify } from "@/lib/utils";

const taxonomySchema=z.object({kind:z.enum(["categories","tags"]),name_en:z.string().trim().min(2).max(80),name_zh:z.string().trim().max(80).optional(),sort_order:z.coerce.number().int().min(0).max(100000).default(0)});
export async function createTaxonomyAction(formData:FormData){await requireAdmin();const parsed=taxonomySchema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Invalid category or tag");const{kind,...value}=parsed.data;const supabase=await createClient();const{error}=await supabase.from(kind).insert({...value,slug:slugify(value.name_en)});if(error)throw new Error(error.message);revalidatePath(`/admin/${kind}`)}
export async function deleteTaxonomyAction(formData:FormData){await requireAdmin();const kind=String(formData.get("kind"));if(kind!=="categories"&&kind!=="tags")throw new Error("Invalid taxonomy");const id=z.uuid().parse(formData.get("id"));const supabase=await createClient();if(kind==="tags"){const{count}=await supabase.from("entity_tags").select("id",{count:"exact",head:true}).eq("tag_id",id);if(count)throw new Error("This tag is in use and cannot be deleted") }else{const tables=["competitions","upcoming_competitions","certificates","education","projects","experiences","awards","files"] as const;for(const table of tables){const{count}=await supabase.from(table).select("id",{count:"exact",head:true}).eq("category_id",id);if(count)throw new Error("This category is in use and cannot be deleted")}}const{error}=await supabase.from(kind).delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath(`/admin/${kind}`)}

const profileSchema=z.object({name_en:z.string().trim().min(2).max(120),name_zh:z.string().trim().max(120).optional(),headline_en:z.string().trim().min(2).max(180),headline_zh:z.string().trim().max(180).optional(),bio_en:z.string().trim().max(1000),bio_zh:z.string().trim().max(1000).optional()});
export async function updateProfileAction(formData:FormData){await requireAdmin();const parsed=profileSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Profile fields are invalid");const supabase=await createClient();const{error}=await supabase.from("site_profile").update(parsed.data).eq("singleton",true);if(error)throw new Error(error.message);revalidatePath("/", "layout");revalidatePath("/admin/site-settings")}

const settingsSchema=z.object({site_title:z.string().trim().min(2).max(120),default_locale:z.enum(["en","zh"]),protected_password_hint:z.string().trim().max(180).optional()});
export async function updateSettingsAction(formData:FormData){await requireAdmin();const parsed=settingsSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Site settings are invalid");const supabase=await createClient();const{error}=await supabase.from("site_settings").update(parsed.data).eq("singleton",true);if(error)throw new Error(error.message);revalidatePath("/admin/site-settings")}

const resumeSchema=z.object({title_en:z.string().trim().min(2).max(120),version_label:z.string().trim().min(1).max(40),file_id:z.uuid(),visibility:z.enum(["public","protected","private"]),allow_download:z.string().optional()});
export async function createResumeAction(formData:FormData){await requireAdmin();const parsed=resumeSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Choose an uploaded PDF and complete the resume fields");const supabase=await createClient();const{data:file}=await supabase.from("files").select("id,mime_type").eq("id",parsed.data.file_id).single();if(!file||file.mime_type!=="application/pdf")throw new Error("Resume file must be an uploaded PDF");const{error}=await supabase.from("resume_versions").insert({title_en:parsed.data.title_en,version_label:parsed.data.version_label,file_id:parsed.data.file_id,visibility:parsed.data.visibility,allow_download:Boolean(parsed.data.allow_download),status:"draft"});if(error)throw new Error(error.message);revalidatePath("/admin/resume")}
